### ISSUE TITLE
pi user cannot access samba shares

### ISSUE THREAD

**Issue by ThomasBrodkorb** [ThomDietrich/openhabian#1]

**Comment by ThomDietrich** [comment]
Hey, you closed this issue, so I guess you realized that you need to use the openhab samba user.
Do you think to have pi as the or as an additional samba user would make more sense?

**Comment by ThomasBrodkorb** [comment]
Would definitely be a good idea.

**Comment by ThomDietrich** [comment]
Think so to. On it.

**Comment by ThomDietrich** [comment]
Hello @ThomasBrodkorb,
I've decided to not make the pi user a second samba users. this introduces some potential problems (e.g. permissions) I'd rather not deal with. I'm open for new arguments or proposals.
