### ISSUE TITLE
Dpkg: warning: ignoring dependency problem

### ISSUE THREAD

**Issue by joshuaherman** [ThomDietrich/openhabian#16]
Using a piB+ v1 is generating many messages about ignoring dependencies. 

V 0.9

**Comment by ThomDietrich** [comment]
Hello joshua,
just tested on a "Raspberry Pi Model B Plus Rev 1.2". The setup ran through without problems - by that I mean, that (1) the LED is blinking like a heartbeat and (2) the status info table is shown when logging in via ssh.
You have these warnings in the raspbian-ua-netinst.log but I *think* they are acceptable. Let me look into that.

**Comment by ThomDietrich** [comment]
These warnings are normal and can be expected harmless.
