### ISSUE TITLE
avahi-daemon

### ISSUE THREAD

**Issue by bodiroga** [ThomDietrich/openhabian#17]
Hi Thomas!

Great work with openHABian, I've tried it with a spare Raspberry Pi 3 that was lying around and everything went perfect! Awesome!

But one thing that I missed (and that it is preinstalled on Raspbian) is to be able to get the Raspberry Pi's IP address without connecting a monitor to it, just using avahi-discover. For that, you only need to install the package "avahi-daemon" to the distribution and then any device on the network can get the its IP address through avahi-discover. Even more, if the Raspberry Pi has the avahi-daemon installed, you can establish an SSH connection just typing "ssh pi@openHABian.local". I know that the package can be installed after the first ssh connection with "sudo apt install avahi-daemon", but IMHO it's worth adding it to the distribution.

Many thanks again for all your hard work and best regards,

Aitor

**Comment by ThomDietrich** [comment]
Hey @bodiroga, I know the name and have no problem in adding it. However, can you point me to an article describing the benefits in more detail? I'm already successfully resolving:

```
$ ssh openHABianPi
pi@openhabianpi's password:
...
```

**Comment by bodiroga** [comment]
Hi @ThomDietrich !

Many thanks for your fast answer!

Unfortunately, I have reinstalled openHABianPi on my Raspberry Pi to try your suggestion, but by default my laptop doesn't resolve the hostname:

aitor@aitor-portatil:~$ ssh openHABianPi
ssh: Could not resolve hostname openhabianpi: Name or service not known
aitor@aitor-portatil:~$ ping openHABianPi
ping: unknown host openHABianPi

Let's see if anyone can jump in and tell us if they can access their Raspberry Pis just by the hostname.

Best regards,

Aitor

**Comment by bodiroga** [comment]
Probably this is the reason why my laptop can't resolve the Raspberry Pi's hostname to an IP address:

https://www.raspberrypi.org/forums/viewtopic.php?f=51&t=46264

As you can see in the third comment, avahi-discover allows network devices to be discovered even if a DNS server is not present in your local network.

Up to you Thomas, you decide if you want to include it in the distribution ;) The only thing I can tell you is that it's shipped by default in both Raspbian and Raspian Lite ;)

**Comment by ThomDietrich** [comment]
>As you can see in the third comment, avahi-discover allows network devices to be discovered even if a DNS server is not present in your local network.

That part is clear to me, I just though every router does that nowadays :) Okay I guess it's decided. I'll include avahi-daemon. Anything else you whould like to see preinstalled? ([list of installed software](https://community.openhab.org/t/openhabian-hassle-free-rpi-image/13379/66?u=thomdietrich))

**Comment by bodiroga** [comment]
Hi Thomas!

It's great to see that you have decided to include the program in the distribution, I'm sure that some new users will welcome your addition ;)

Many thanks for all the work you are doing on openHABian, it's never been so easy to have a working openHAB enviroment!
