### ISSUE TITLE
openhabian-setup.sh fail to install openhab

### ISSUE THREAD

**Issue by Tomtibo** [ThomDietrich/openhabian#19]
What I'v done:
Download openhabian-ua-netinst-20160915-git9e034e7.img
Rip to sd card using dd
Boot it up on a RaspberryPi2, with a monitor plugged in, to see what's happen!

Issue:
The script failed around line 267
The repository was added just fine, but openhab2-offline was not installed 
A manual apt install openhab2-offline work fine.

Anybody else experimenting this issue?

Edit: Maybe the repository is not fine after all...

` W: Failed to fetch https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ws/distributions/openhab-offline/target/apt-repo/Packages  HttpError404 `

**Comment by ThomDietrich** [comment]
This did never happen before. I had a successful run yesterday. I'd suspect that to be a temporary outage on the server side. Could you try once more?

**Comment by Tomtibo** [comment]
raspbian-ua-netinst.log show an error.
`[openHABian] Adding openHAB 2 Snapshot repositories to sources.list.d... FAILED`
I guess your right! Now the repository is online!

**Comment by ThomDietrich** [comment]
Wonderful. Enjoy ;)

**Comment by brrrglund** [comment]
Had the same problem today, two times in a row. Is there any convenient way to see if the server is working?

**Comment by ThomDietrich** [comment]
openHAB is currently switching over to a new server, this problem will not occur in the future ;)

**Comment by brrrglund** [comment]
Thanks, tried again this morning and it worked =]
