### ISSUE TITLE
"sudo: unable to open /var/lib/sudo/ts/pi: Read-only file system" issue

### ISSUE THREAD

**Issue by rlajos** [ThomDietrich/openhabian#32]
After apt-get update, upgrade (upgrade has chrashed before finishing...) I get the error message: sudo: unable to open /var/lib/sudo/ts/pi: Read-only file system

Is threre any fix for that? (install from 4 days ago)

Thank you,

Lajos

**Comment by ThomDietrich** [comment]
Hey! Sounds like a problem with your filesystem. Try a reboot first. Next check your filesystem for errors. Your SD card may be corrupted or damaged.

Also check http://askubuntu.com/a/197468

**Comment by rlajos** [comment]
Ja, danke. Habe es schon versucht, keine Ergebniss…

sudo fsck -Af –M hilft auch nicht…

L

**Comment by ThomDietrich** [comment]
Is this issue resolved?

**Comment by rlajos** [comment]
Hallo Thom,

Unfortunately not... it can be an SD card problem, once I had disk error with this card already.
I will buy a new card and reinstall the whole stuff from the strach.

Danke,
Lajos

rlajos iphone

On 2016. Nov 8., at 11:13, Thomas Dietrich <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this issue resolved?

-

**Comment by ThomDietrich** [comment]
Okay, ich wünsch dir viel Erfolg und hoffe du kannst deine Konfiguration wieder vollständig herstellen.
Ich schließ das Ticket hier, öffne es einfach wieder, solltest du weitere Fragen haben ;)

**Comment by rlajos** [comment]
Danke Dir,

Gruss:
Lajos
