### ISSUE TITLE
Option to enable audio

### ISSUE THREAD

**Issue by kubawolanin** [ThomDietrich/openhabian#40]
Hello there,

Since there are some ongoing development efforts on [Audio add-ons for openHAB2](http://docs.openhab.org/features/multimedia.html), it would be a good opportunity to enable audio by default.

When I've set up latest openHABian on my Raspberry PI3, I observed that there were no audio devices enabled. I tested it with `aplay -l`.

What I did was modifying `/boot/config.txt` by adding the following line:

	dtparam=audio=on

Now my audio works flawlessly :)

Wouldn't it be good to have some Advanced Option available that would setup audio in RPi?
I don't know if the solution above applies to RPi2. 

Cheers

**Comment by ThomDietrich** [comment]
Hey! I'd be okay with that. Any downsides to activating audio or influences on other hardware? Do you know the reason for it not being on by default?

**Comment by kubawolanin** [comment]
Hi @ThomDietrich. I'm not aware of any downsides and am not sure why it wasn't activated by default.

**Comment by ThomDietrich** [comment]
@kubawolanin I've added that feature to the main setup.
