### ISSUE TITLE
Can’t copy image to another SD card as openhabian uses whole SD card by default (8GB or 16GB SD card)

### ISSUE THREAD

**Issue by palatia** [ThomDietrich/openhabian#46]
SD card comes usually with different sizes of a few bytes, so using an SD copy program don’t allow you to copy the image to another SD card. It might better to not take the always the full available bytes per SD card. An better option might be to take a bit less as available like 7.8 GB or 15.8 GB) … sure a few bytes are lost but you won’t run into issues using an SD image copy program.

**Comment by ThomDietrich** [comment]
Hey @palatia, that's a good idea! I've however no saying in that.
Could you create a new (nearly identical) ticket at https://github.com/debian-pi/raspbian-ua-netinst ? That's the base project we are using for openHABian and your idea needs to be implemented there.

**Comment by palatia** [comment]
sure, no problem. i haved added it here - 
https://github.com/debian-pi/raspbian-ua-netinst/issues/439

Thanks for the link to the downsizer script. Looks easier as the steps i were using.

**Comment by ThomDietrich** [comment]
Additionally I just found https://github.com/Drewsif/PiShrink
