### ISSUE TITLE
optional component: eibd (KNX)

### ISSUE THREAD

**Issue by ThomDietrich** [ThomDietrich/openhabian#7]

**Comment by staehler** [comment]
It seems, there is no eibd-package for ARM, so eibd needs to be compiled :-( A quite good ressource on this you find [here](http://michlstechblog.info/blog/raspberry-pi-eibd-with-a-knx-usb-interface/).

FInally the eibd-config depends on the KNX-Interface, which could be USB, RS232 or IP, but it seems that the /etc/init.d/eibd script can detect it automatically. Al least it does it for my USB interface.

I would suggest to compile the eibd once and deploy it (optionally) with your distribution. As mentioned, there is no eibd binary available for ARM. The user needs to compile it by himself. This means, there has to be a complete building environment on the raspberry. At least for this one compile run. As eibd isn't developed further, there is no great risk to get outdated ;-)
Another and new branch of the eibd is [knxd](https://github.com/knxd/knxd). But that's all I know about it.

**Comment by ThomDietrich** [comment]
I looked into knxd and there has been quite the activity. That's why I'm not sure what's the best approach to incorporate KNX. Hence I will leave this task for later and trust into the next person to come up with the "right" setup to post it here ;)

**Comment by staehler** [comment]
As I have my new raspi3 since yesterday, I can show, what I needed to do to get knxd running.

1. copy this [script ](http://michlstechblog.info/blog/download/electronic/install_knxd_systemd.sh) from http://michlstechblog.info/blog/raspberry-pi-eibd-with-a-knx-usb-interface/
2. Then run the script: 
```
  wget http://michlstechblog.info/blog/download/electronic/install_knxd_systemd.sh
  chmod +x ./install_knxd_systemd.sh
  ./install_knxd_systemd.sh
```
3. choose the right interface in /etc/defaults/knxd
4. start the service

For me it's running now, but there are some minor bugs in start scripts, which may needed to be corrected (at least, when a USB-interface is used).
I'll try to get contact to the developer.

**Comment by ThomDietrich** [comment]
Hey, I've included these steps in a first draft and the script is running right now. I am not really happy with a few steps in the script though. A unnecessary "apt upgrade" in the beginning, no error catching, ...
Maybe we should upload and modify the script here in this repository?

**Comment by staehler** [comment]
It's up to you. The best way would be a deb-file, which could be just 
installed via dpkg.
Then all the build-stuff (make, gcc, etc.) wouldn't have to be 
installed, which wastes space and is not anymore needed after compilation.
Unfortunately I have no idea how to build a deb-file.
I hope the community around knxd is going to do this in the future.



Am 05-Sep-2016 02:32:29 +0200 schrieb notifications@github.com:

    Hey, I've included these steps in a first draft and the script is
    running right now. I am not really happy with a few steps in the
    script though. A unnecessary "apt upgrade" in the beginning, no
    error catching, ...
    Maybe we should upload and modify the script here in this repository?

    —
    You are receiving this because you commented.
    Reply to this email directly, view it on GitHub
    <https://github.com/ThomDietrich/openhabian/issues/7#issuecomment-244637651>,
    or mute the thread

**Comment by ThomDietrich** [comment]
This is still an open issue.
The simplest solution is now part of the master branch but improvement is needed.
@staehler did you reach out to the developer?

**Comment by staehler** [comment]
Yes, he fixed the issue I've found.
If you have further requests, contact him via the commecnts section of his site. He responded quite fast.

**Comment by ThomDietrich** [comment]
Hello, as with 1wire, would be great if you provided me with a short before and after text!

**Comment by staehler** [comment]
Well I'm no expert with knxd as I run eibd at the moment, but this text should be fine:

---
This will install knxd (successor to eibd) to support your KNX bus system. Please edit **/etc/default/knxd** to meet your interface requirements. For further information on knxd options, please type **knxd --help**.
---
Maybe you want to mention the website, where the installer is from, as the maintainer could be contacted, in case of problems via the forum comments section.

**Comment by ThomDietrich** [comment]
Added in https://github.com/ThomDietrich/openhabian/commit/89137209dcfeade3aa718468ce43eadebe7b7ec3
Thanks!!
