### ISSUE TITLE
optional component: owserver (1wire)

### ISSUE THREAD

**Issue by ThomDietrich** [ThomDietrich/openhabian#8]

**Comment by staehler** [comment]
As far as I know, you need to install 1wire, there are two packages (and maybe other dependencies) necessary:
apt-get install owfs-common owserver

Depending on the 1wire interface there may be one edit in the /etc/owfs.conf necessary. I needed to change to (depends on the 1wire interface):

> server:  device = /dev/ttyUSB0

I added this to /etc/owfs.conf as well, as systemd needs it for consitent operation:

> pid_file=/var/run/owfs/owserver.pid

If you want to start with systemd, than this configuration could work:

> [Unit]
> Description=OWServer - 1wire TCP server
> Documentation=man:owserver(1)
> After=syslog.target network.target
> 
> [Service]
> Type=forking
> User=root
> WorkingDirectory=/root
> ExecStart=/usr/bin/owserver -c /etc/owfs.conf
> PIDFile=/var/run/owfs/owserver.pid
> Restart=on-failure
> KillSignal=SIGKILL
> 
> [Install]
> WantedBy=multi-user.target

That's what work in my environment. Maybe there could come some feature requests in the future, when other users need more adaption to owfs.conf.

**Comment by ThomDietrich** [comment]
Thank you. I will add it this evening or tomorrow. Will you be available for testing in the next few days? I do not like that one needs to add the service manually. Hopefully by now there is one inside the package.

**Comment by staehler** [comment]
Hmm, I am running OH on a virtual machine (debian). My raspi is from the first generation and out of order. I'm thinking about buying the raspi3. Than I'm able to beta test.

**Comment by staehler** [comment]
Since yesterday I have my raspi3 and your openhasbian running. The installation was absolutley perfect nothing to do manually ...

I installed 1wire als follows und it is running:
````
# Necessary
apt install owserver
# Usefull
apt install ow-shell
apt install usbutils
````
Then just a few adoptions to /etc/owfs.conf and service start owserver. That's it!
The adoptions depend on the 1wire interface:
my owfs.conf looks like

```
! server: server = 192.168.2.xxx:4304
server: device = /dev/ttyUSB0
server: port = 192.168.2.xxx:4304
```

**Comment by ThomDietrich** [comment]
Got that included as well - no surprise as it's only one command :)

The real task to get to next is, to write a few short sentences before and after the setup to tell the user what's going to happen an what he has to do next.

"this will install owserver, ow-shell and usbutils to ... For more details, have a look at http://..."

"Setup was successful. Next, please configure your system in /etc/owfs.conf"

It would be amazing to get these from you ;)

```
[02:40:56] pi@openHABianPi:~$ cat /etc/owfs.conf
# Sample configuration file for the OWFS suite for Debian GNU/Linux.
#
#
# This is the main OWFS configuration file. You should read the
# owfs.conf(5) manual page in order to understand the options listed
# here.

######################## SOURCES ########################
#
# With this setup, any client (but owserver) uses owserver on the
# local machine...
! server: server = localhost:4304
#
# ...and owserver uses the real hardware, by default fake devices
# This part must be changed on real installation
server: FAKE = DS18S20,DS2405
#
# USB device: DS9490
#server: usb = all
#
# Serial port: DS9097
#server: device = /dev/ttyS1
#
# owserver tcp address
#server: server = 192.168.10.1:3131
#
# random simulated device
#server: FAKE = DS18S20,DS2405
#
######################### OWFS ##########################
#
#mountpoint = /mnt/1wire
#allow_other
#
####################### OWHTTPD #########################

http: port = 2121

####################### OWFTPD ##########################

ftp: port = 2120

####################### OWSERVER ########################

server: port = localhost:4304
```

```
[02:41:16] pi@openHABianPi:~$ owdir /
/10.67C6697351FF
/05.4AEC29CDBAAB
/bus.0
/uncached
/settings
/system
/statistics
/structure
/simultaneous
/alarm
```

**Comment by staehler** [comment]
As far as I used your installer, it was unattended. So, when the user has the ability to make decissions (which software to install further)?   As described by you, I would add information like this. The User needs to select 1Wire-support, than a message like this could appear:   "this will install owserver to support 1wire functionality in general, ow-shell and usbutils are helpfull tools to check USB (lsusb) and 1wire function (owdir, owread). For more details, have a look at

**Comment by ThomDietrich** [comment]
It was unattended yes. I have started to include a menu for when it is not called unattended.
There is a simple text based menu for testing, before the merge it will be replaced by some graphical menu.

https://github.com/ThomDietrich/openhabian/blob/refactor-menu/openhabian-setup.sh#L304-L319

Thank you for the text. Can you provide "have a look at ..."?

**Comment by staehler** [comment]
Ups, my text is not complete. I wrote the following:

"this will install owserver to support 1wire functionality in general, ow-shell and usbutils are helpfull tools to check USB (lsusb) and  1wire function (owdir, owread). For more details, have a look at http://owfs.com"
 
After installation:
 
"Setup was successful. Next, please configure your system in /etc/owfs.conf.
Use # for deactivate a line. All you should have to change is the following. Deactivate 
server: FAKE = DS18S20,DS2405
and activate one of these most common options (depending on your device). Just remove # in front of the line, to activate this device
#server: usb = all
#server: device = /dev/ttyS1
#server: device = /dev/ttyUSB0
Use # for comments.
 
Check your configuration for example by using the command "owdir /" (if you are on localhost), which should show your 1wire devices after some seconds of 1wire initialisation."

**Comment by ThomDietrich** [comment]
Hey @staehler, this is now part of stable openHABian through the menu. I did not yet add your strings.

**Comment by ThomDietrich** [comment]
This is now completed and part of v0.9
https://community.openhab.org/t/openhabian-hassle-free-rpi-image/13379/61
Would be great if you came around to test it soon ;)

**Comment by stellanel** [comment]
Hi
Usually  documentation and the community solves my problems. But openbaian owserver installation is so new that I can not find anything on Google!
I am migrating an old owfs installation on NSLU2/unslung 6.? to Pi2B/Openhabian.
Installing went just fine, I "love" the openhabian initiative ! 
My test rig is Bus Master=usb ds9490r, ds1820 and Louis Swart LCD Screen Controller 
owdir /
/10.12E15F010800
/81.B74B2F000000
/bus.1
/uncached
/settings
/system
/statistics
/structure
/simultaneous
/alarm
onewire="deviceId=FF.950300000100 from my test Item is missed in the owdir list
I used "owfs -u --usb_regulartime --allow_other /mnt/1wire" as the start command on NSLU2/unslung!
The botton line: "--usb_regulartime" enable owserver to use Louis Swart LCD Screen Controller!
As a first step i can edit the start script to varify my usumptions, but i need information on where i can find the related script.
Kind Regards /Stellan

**Comment by ThomDietrich** [comment]
@staehler can you help here?

**Comment by staehler** [comment]
Unfortunately, I can't. This issue seems to be not a problem with openhabian, but a general onewire configuration.
So far I understood, this owserver was configured correctly in an older installation and worked fine. So why you don't use this /etc/owfs.conf in your new installation? If some devices don't appear, this might be a problem with onewire itself or with the owfs-configuration.
onewire in general is sometimes a little tricky and if connected via USB it could work on one computer and might not work on another computer. As computer works like an antenna and disturb onewire, a USB decoupling is recommended. As well there might help some capacitors in the bus line to reduce errors.

**Comment by stellanel** [comment]
Hello
Sorry for late reply, now back from vacation! Yes, you helped me actually! I added "usb_regulartime" in the file owfs.conf!    "Owdir" now shows the "Louis Swart LCD Screen Controller"!
Continuing to lern more about "systemctl" in order to start "owhttpd" and also, what must be done when I get "Connection refused" when I run "ownet" based owPerl/owPython scripts! Thanks!

**Comment by stellanel** [comment]
Testing "owserver" installed with openhabian 1,2 on RP12B give me these results and problems!
All my test, writing to "Louis Swart LCD Screen Controller" using owdir ,owhttpd and perl script(ownet), is fully functional. But i receive the following error from:

* Openhab 1.8.3 with onewire binding 1.8.3 on Synology DSM 6.0:
"2017-04-01 19:51:07.510 [ERROR] [o.o.b.o.i.c.OneWireConnection ] - writing 01 Apr 19:51:05 to path FF.950300000100/line16.3/message attempt 3 throws exception
org.owfs.jowfsclient.OwfsException: Error -1"

* and Openhab2 with onewire binding 1.9.0 on RPI2B Openhabian :  
"2017-04-01 19:53:31.721 [ERROR] [nternal.connection.OneWireConnection] - Writing 3333333333333333 to path FF.950300000100/line16.3/message attempt 3 threw an exception
org.owfs.jowfsclient.OwfsException: Error -1"

These bindings have no problem reading DS1820 temperature device!

The system i am intending to migrate from, owserver on (NSLU2) Unslung 6.8 , show no problems at all with the same test setup! 
Kind Regards /Stellan
